LRAC-8139
alexcandidos/liferay-portal pull request #481
Opened 2021-07-21 20:13 UTC by ViniLopes20

2021-07-21 20:13 UTC, liferay-continuous-integration commented
Please only forward critical changes to Brian Chan during stabilization. Nonurgent changes should wait until the ongoing 7.4 DXP EP3 & CE GA3 release has been completed. For more details on the release timeline and status, see <a href="https://liferay.slack.com/archives/C03BTCQBQ">product-delivery</a>.

2021-07-21 20:13 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2021-07-21 22:15 UTC, alexcandidos commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/analyticscloud/ActiveIndividuals.testcase
> +		ACProperties.switchProperty(propertyName = "Liferay DXP Combined Property");
hey @ViniLopes20 , I think you forgot to pass the propertyname value instead of "Liferay DXP..."

2021-07-21 22:18 UTC, alexcandidos commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/analyticscloud/ActiveIndividuals.testcase
> +		AssertElementPresent(locator1 = "ACIndividualsDashboard#ACTIVE_INDIVIDUAL_CHART");
Hey @ViniLopes20 , I was taking a look at this path and it is only checking any option selected on the time filter dropdown. As well as, in this test we should validate if the graph shows activities when switching to the last 24 hours... So we should investigate for example how to validate a blue bar that is probably shown based on the DXP activities. ;)

2021-07-21 22:19 UTC, alexcandidos commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/analyticscloud/ActiveIndividuals.testcase
>  	@ignore = "true"
hi @ViniLopes20 , please remove the ignore when the test is done :)

2021-07-21 22:23 UTC, alexcandidos commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/analyticscloud/ActiveIndividuals.testcase
> +		AssertElementPresent(locator1 = "ACIndividualsDashboard#ACTIVE_INDIVIDUAL_CHART");
For this, please, take a look at these tests created by Calvin, I think he was validating something very similar to what you are trying to validate here:

```
ActiveIndividuals#CanSetDataWithCustomRangeOnIndividualActivitiesCard
ActiveIndividuals#CanSetEmptyDataCustomRangeOnIndividualActivitiesCard
```

2021-07-21 22:24 UTC, alexcandidos requested changes
Hey @ViniLopes20 , I just left a few comments for to you take a look at! 

Thanks!

2021-07-22 21:37 UTC, ViniLopes20 commented
ci:forward

2021-07-22 21:37 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

The pull request will automatically be forwarded to the user `brianchandotcom` if the following test suites pass:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

2021-07-22 21:37 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-27.liferay.com/job/test-portal-source-format/478/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-27.liferay.com//userContent/jobs/test-portal-source-format/builds/478/jenkins-report.html">here</a>.</b></p>

2021-07-22 21:39 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 2 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/8c974b6b7e41280b50c8620ce191590f253b65a4">8c974b6b7e41280b50c8620ce191590f253b65a4</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/ViniLopes20/liferay-portal/tree/LRAC-8139">LRAC-8139</a><br/>Branch GIT ID: <a href="https://github.com/ViniLopes20/liferay-portal/commit/b83f5a534496bb57c61e9b8ffe28d379109f7ea1">b83f5a534496bb57c61e9b8ffe28d379109f7ea1</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-27.liferay.com/job/test-portal-source-format/478/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-source-format/builds/478/jenkins-report.html">here</a>.</h5></details></html>

2021-07-22 21:40 UTC, liferay-continuous-integration commented
All required test suite(s) passed.
Forwarding pull request to `brianchandotcom`.
[Console](https://test-1-27.liferay.com/job/test-portal-source-format/478//consoleFull)

2021-07-22 21:40 UTC, liferay-continuous-integration commented
All required test suite(s) passed.
Forwarding pull request to `brianchandotcom`.
[Console](https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest(master)/502//consoleFull)

2021-07-22 21:40 UTC, liferay-continuous-integration commented
Pull request has been successfully forwarded to https://github.com/brianchandotcom/liferay-portal/pull/104695
[Console](https://test-1-27.liferay.com/job/test-portal-source-format/478//consoleFull)

2021-07-22 21:40 UTC, closed without merging

2021-07-22 21:40 UTC, liferay-continuous-integration commented
Pull request has been successfully forwarded to https://github.com/brianchandotcom/liferay-portal/pull/104696
[Console](https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest(master)/502//consoleFull)

2021-07-22 21:41 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-27.liferay.com/job/test-portal-source-format/478/">test-portal-source-format#478</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-source-format/builds/478/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/alexcandidos/liferay-portal/pull/481">alexcandidos#481</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1548931975">[master] ci:test:sf - ViniLopes20 &gt; alexcandidos - PR#481 - 2021-07-22[14:37:29]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-27.liferay.com/job/publish-testray-report/749/">publish-testray-report#749</a><br/></div></div>

2021-07-22 21:43 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest(master)/502/">test-portal-acceptance-pullrequest(master)#502</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/502/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/alexcandidos/liferay-portal/pull/481">alexcandidos#481</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1548931996">[master] ci:test:relevant - ViniLopes20 &gt; alexcandidos - PR#481 - 2021-07-22[14:37:29]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-27.liferay.com/job/publish-testray-report/750/">publish-testray-report#750</a><br/></div></div>