Activities
alexcandidos/liferay-portal pull request #510
Opened 2021-08-05 20:54 UTC by rafaellajordao

2021-08-05 20:54 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2021-08-05 21:55 UTC, ViniLopes20 commented
Hi, @rafaellajordao. Commits always starting with LRAC-XXXX (XXX -> Your branch number).

because it won't give an error when calling `ci:forward`

2021-08-05 23:03 UTC, alexcandidos commented
Also @rafaellajordao , please add the ticket ID in front of the PR message :)

2021-08-06 16:38 UTC, rafaellajordao commented
Fixed! @alexcandidos and @ViniLopes20!

2021-08-06 17:25 UTC, ViniLopes20 commented
ci:test:sf

2021-08-06 17:25 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-30.liferay.com/job/test-portal-source-format/117/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-30.liferay.com//userContent/jobs/test-portal-source-format/builds/117/jenkins-report.html">here</a>.</b></p>

2021-08-06 17:27 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 2 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/2bfe5e75c257abc7adb4e80c01f35217880b0edd">2bfe5e75c257abc7adb4e80c01f35217880b0edd</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/rafaellajordao/liferay-portal/tree/Activities">Activities</a><br/>Branch GIT ID: <a href="https://github.com/rafaellajordao/liferay-portal/commit/4a8647a95e6c4eb62aa398c62d74f1e225c56fa8">4a8647a95e6c4eb62aa398c62d74f1e225c56fa8</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-30.liferay.com/job/test-portal-source-format/117/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-30.liferay.com/userContent/jobs/test-portal-source-format/builds/117/jenkins-report.html">here</a>.</h5></details></html>

2021-08-07 00:35 UTC, alexcandidos commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/analyticscloud/SitesActivities.testcase
> +	@priority = "5"
Hi @rafaellajordao , this tc is priority 3 on the test map.

2021-08-07 00:36 UTC, alexcandidos commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/analyticscloud/SitesActivities.testcase
> +	@priority = "5"
Hi @rafaellajordao , this tc is priority 3 on the test map.

2021-08-07 00:36 UTC, alexcandidos commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/analyticscloud/SitesActivities.testcase
> +	@priority = "5"
Hi @rafaellajordao , this tc is priority 4 on the test map.

2021-08-07 00:37 UTC, alexcandidos commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/analyticscloud/SitesActivities.testcase
> +	@priority = "5"
Hi @rafaellajordao , this tc is priority 3 on the test map.

2021-08-07 00:38 UTC, alexcandidos commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/analyticscloud/SitesActivities.testcase
> +		// TODO LRAC-8290 CanUniqueVisitorsLabelShowSitesDashboards
hi @rafaellajordao it should be this // TODO LRAC-8290 CanUniqueVisitorsLabelShowPagesDashboards

2021-08-07 00:40 UTC, alexcandidos requested changes
hi @rafaellajordao , please see my comments and update the priority of some tests.

Thanks!

2021-08-07 04:10 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-30.liferay.com/job/test-portal-source-format/117/">test-portal-source-format#117</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-30.liferay.com/userContent/jobs/test-portal-source-format/builds/117/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/alexcandidos/liferay-portal/pull/510">alexcandidos#510</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1551942609">[master] ci:test:sf - rafaellajordao &gt; alexcandidos - PR#510 - 2021-08-06[10:25:25]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-30.liferay.com/job/publish-testray-report/342/">publish-testray-report#342</a><br/></div></div>

2021-08-09 21:56 UTC, alexcandidos commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/analyticscloud/SitesActivities.testcase
> +	}
hi @rafaellajordao , this tc is a priority 4 in our test map.

2021-08-09 21:58 UTC, alexcandidos commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/analyticscloud/SitesActivities.testcase
> +	}
hi @rafaellajordao , this tc is a priority 5 in our test map.

2021-08-09 21:58 UTC, alexcandidos commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/analyticscloud/SitesActivities.testcase
> +	}
hi @rafaellajordao , this tc is a priority 5 in our test map.

2021-08-09 21:59 UTC, alexcandidos commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/analyticscloud/SitesActivities.testcase
> +	}
hi @rafaellajordao , this tc is a priority 5 in our test map.

2021-08-09 21:59 UTC, alexcandidos commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/analyticscloud/SitesActivities.testcase
> +	@description = "Feature ID: Legacy | Automation ID: LRAC-8279 | Test Summary: Site Activity Card: Can hover over a point on the graph to get detailed stats"
hi @rafaellajordao , this tc is a priority 5 in our test map.

2021-08-09 22:00 UTC, alexcandidos commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/analyticscloud/SitesActivities.testcase
> +	}
hi @rafaellajordao , this tc is a priority 5 in our test map.

2021-08-09 22:00 UTC, alexcandidos commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/analyticscloud/SitesActivities.testcase
> +	}
hi @rafaellajordao  this tc is a priority 5 in our test map.

2021-08-09 22:01 UTC, alexcandidos commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/analyticscloud/SitesActivities.testcase
> +	}
hi @rafaellajordao , this tc is a priority 5 in our test map.

2021-08-09 22:02 UTC, alexcandidos commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/analyticscloud/SitesActivities.testcase
> +	}
hi @rafaellajordao , this tc is a priority 3 in our test map.

2021-08-09 22:03 UTC, alexcandidos requested changes
hi @rafaellajordao , please take a look at my comments, some priorities are wrong.

Thanks!

2021-08-10 18:24 UTC, alexcandidos commented
Hi @rafaellajordao , this test `CanSitesActivityTimeFilterUseCustomRange` is still with the wrong priority, it should be 5 and not 3.

Could you please fix it? Thanks!

2021-08-10 18:46 UTC, alexcandidos commented
Hi @rafaellajordao , Thanks for working on it!

The code looks good to me!

2021-08-10 18:46 UTC, alexcandidos approved these changes
Hi @rafaellajordao , Thanks for working on it!

The code looks good to me!

2021-08-10 18:47 UTC, alexcandidos commented
ci:forward

2021-08-10 18:47 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

The pull request will automatically be forwarded to the user `brianchandotcom` if the following test suites pass:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

2021-08-10 18:48 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-28.liferay.com/job/test-portal-source-format/427/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-28.liferay.com//userContent/jobs/test-portal-source-format/builds/427/jenkins-report.html">here</a>.</b></p>

2021-08-10 18:49 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 2 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/dedd00197744b6f5a805793b296d9c8da5c105e0">dedd00197744b6f5a805793b296d9c8da5c105e0</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/rafaellajordao/liferay-portal/tree/Activities">Activities</a><br/>Branch GIT ID: <a href="https://github.com/rafaellajordao/liferay-portal/commit/3f14675ce2b4d5cb2f7bb41f790752893b34cf42">3f14675ce2b4d5cb2f7bb41f790752893b34cf42</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-28.liferay.com/job/test-portal-source-format/427/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-28.liferay.com/userContent/jobs/test-portal-source-format/builds/427/jenkins-report.html">here</a>.</h5></details></html>

2021-08-10 18:49 UTC, liferay-continuous-integration commented
All required test suite(s) passed.
Forwarding pull request to `brianchandotcom`.
[Console](https://test-1-28.liferay.com/job/test-portal-source-format/427//consoleFull)

2021-08-10 18:50 UTC, liferay-continuous-integration commented
Pull request has been successfully forwarded to https://github.com/brianchandotcom/liferay-portal/pull/105347
[Console](https://test-1-28.liferay.com/job/test-portal-source-format/427//consoleFull)

2021-08-10 18:50 UTC, closed without merging

2021-08-10 18:54 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-28.liferay.com/job/test-portal-source-format/427/">test-portal-source-format#427</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-28.liferay.com/userContent/jobs/test-portal-source-format/builds/427/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/alexcandidos/liferay-portal/pull/510">alexcandidos#510</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1552492825">[master] ci:test:sf - rafaellajordao &gt; alexcandidos - PR#510 - 2021-08-10[11:47:37]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-28.liferay.com/job/publish-testray-report/1329/">publish-testray-report#1329</a><br/></div></div>