CohortAnalysis
alexcandidos/liferay-portal pull request #513
Opened 2021-08-05 21:23 UTC by rafaellajordao

2021-08-05 21:23 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2021-08-05 21:50 UTC, ViniLopes20 commented
Hi, @rafaellajordao. Commits always starting with LRAC-XXXX (XXX -> Your branch number).

because it won't give an error when calling `ci:forward`

2021-08-05 23:08 UTC, alexcandidos commented
hi @rafaellajordao , please see my comment here https://github.com/alexcandidos/liferay-portal/pull/510#issuecomment-893875039

2021-08-06 16:45 UTC, rafaellajordao commented
Fixed! @alexcandidos and @ViniLopes20!

2021-08-06 17:26 UTC, ViniLopes20 commented
ci:test:sf

2021-08-06 17:26 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-25.liferay.com/job/test-portal-source-format/3225/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-25.liferay.com//userContent/jobs/test-portal-source-format/builds/3225/jenkins-report.html">here</a>.</b></p>

2021-08-06 17:28 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 2 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/2bfe5e75c257abc7adb4e80c01f35217880b0edd">2bfe5e75c257abc7adb4e80c01f35217880b0edd</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/rafaellajordao/liferay-portal/tree/CohortAnalysis">CohortAnalysis</a><br/>Branch GIT ID: <a href="https://github.com/rafaellajordao/liferay-portal/commit/7c1c7922d6e33fed4d165290264a9a80515f20ac">7c1c7922d6e33fed4d165290264a9a80515f20ac</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-25.liferay.com/job/test-portal-source-format/3225/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-source-format/builds/3225/jenkins-report.html">here</a>.</h5></details></html>

2021-08-07 00:51 UTC, alexcandidos commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/analyticscloud/SitesCohortAnalysis.testcase
> +	test AssertSitesCohortAnalysisSortAnonymousVisitors {
hi @rafaellajordao , this tc is a priority 3 on the test map.

2021-08-07 00:52 UTC, alexcandidos requested changes
Hi @rafaellajordao , please update one of the tcs priorities. Thanks!

2021-08-07 00:56 UTC, alexcandidos commented
Hi @rafaellajordao , your last two PRs were with the wrong ticket id, they were not pointing to the ticket you had crated to commit the stubs. 

this was pointing to LRAC-8325 instead of LRAC-8328

2021-08-07 04:32 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-25.liferay.com/job/test-portal-source-format/3225/">test-portal-source-format#3225</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-source-format/builds/3225/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/alexcandidos/liferay-portal/pull/513">alexcandidos#513</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1551946676">[master] ci:test:sf - rafaellajordao &gt; alexcandidos - PR#513 - 2021-08-06[10:26:15]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-25.liferay.com/job/publish-testray-report/9806/">publish-testray-report#9806</a><br/></div></div>

2021-08-09 22:06 UTC, alexcandidos approved these changes
Hi @rafaellajordao , Thanks for working on it!

The code looks good to me!

2021-08-09 22:06 UTC, alexcandidos commented
ci:forward

2021-08-09 22:06 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

The pull request will automatically be forwarded to the user `brianchandotcom` if the following test suites pass:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

2021-08-09 22:07 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-31.liferay.com/job/test-portal-source-format/61/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-31.liferay.com//userContent/jobs/test-portal-source-format/builds/61/jenkins-report.html">here</a>.</b></p>

2021-08-09 22:09 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 2 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/99e68815843e30f8817d839e793fa0e7a854f91a">99e68815843e30f8817d839e793fa0e7a854f91a</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/rafaellajordao/liferay-portal/tree/CohortAnalysis">CohortAnalysis</a><br/>Branch GIT ID: <a href="https://github.com/rafaellajordao/liferay-portal/commit/ec7d7047905bae78802719bb78ebbeef67392498">ec7d7047905bae78802719bb78ebbeef67392498</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-31.liferay.com/job/test-portal-source-format/61/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-31.liferay.com/userContent/jobs/test-portal-source-format/builds/61/jenkins-report.html">here</a>.</h5></details></html>

2021-08-09 22:09 UTC, liferay-continuous-integration commented
All required test suite(s) passed.
Forwarding pull request to `brianchandotcom`.
[Console](https://test-1-31.liferay.com/job/test-portal-source-format/61//consoleFull)

2021-08-09 22:09 UTC, liferay-continuous-integration commented
Pull request has been successfully forwarded to https://github.com/brianchandotcom/liferay-portal/pull/105289
[Console](https://test-1-31.liferay.com/job/test-portal-source-format/61//consoleFull)

2021-08-09 22:09 UTC, closed without merging