LRAC-8343
alexcandidos/liferay-portal pull request #517
Opened 2021-08-06 12:35 UTC by LucasAcacio

2021-08-06 12:35 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2021-08-07 01:01 UTC, alexcandidos commented
ci:test:sf

2021-08-07 01:02 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-28.liferay.com/job/test-portal-source-format/395/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-28.liferay.com//userContent/jobs/test-portal-source-format/builds/395/jenkins-report.html">here</a>.</b></p>

2021-08-07 01:04 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 2 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/85ec5558383ead431ef152d67df3af5c556ac69a">85ec5558383ead431ef152d67df3af5c556ac69a</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/LucasAcacio/liferay-portal/tree/LRAC-8343">LRAC-8343</a><br/>Branch GIT ID: <a href="https://github.com/LucasAcacio/liferay-portal/commit/0f607d2840c10a20ad1f3eed4a14937a045c32b4">0f607d2840c10a20ad1f3eed4a14937a045c32b4</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-28.liferay.com/job/test-portal-source-format/395/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-28.liferay.com/userContent/jobs/test-portal-source-format/builds/395/jenkins-report.html">here</a>.</h5></details></html>

2021-08-07 14:06 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-28.liferay.com/job/test-portal-source-format/395/">test-portal-source-format#395</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-28.liferay.com/userContent/jobs/test-portal-source-format/builds/395/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/alexcandidos/liferay-portal/pull/517">alexcandidos#517</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1551977908">[master] ci:test:sf - LucasAcacio &gt; alexcandidos - PR#517 - 2021-08-06[18:02:02]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-28.liferay.com/job/publish-testray-report/1222/">publish-testray-report#1222</a><br/></div></div>

2021-08-09 14:57 UTC, alexcandidos commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/analyticscloud/PagesList.testcase
> +
hey @LucasAcacio , please make sure the test on the TODO comment is the same of the test ;)

2021-08-09 14:57 UTC, alexcandidos commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/analyticscloud/PagesList.testcase
> +
hey @LucasAcacio , please make sure the test on the TODO comment is the same of the test ;)

2021-08-09 14:58 UTC, alexcandidos requested changes
Hi @LucasAcacio , please take a look at my comments.

2021-08-09 16:49 UTC, LucasAcacio commented
Required changes done

2021-08-09 16:49 UTC, LucasAcacio commented
ci:test:sf

2021-08-09 16:50 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-25.liferay.com/job/test-portal-source-format/3244/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-25.liferay.com//userContent/jobs/test-portal-source-format/builds/3244/jenkins-report.html">here</a>.</b></p>

2021-08-09 16:51 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 2 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/435a75f13a316518c766bd21e5721e6fe2b91b20">435a75f13a316518c766bd21e5721e6fe2b91b20</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/LucasAcacio/liferay-portal/tree/LRAC-8343">LRAC-8343</a><br/>Branch GIT ID: <a href="https://github.com/LucasAcacio/liferay-portal/commit/75493fdbf783016a189a680254e185b1da43c2c5">75493fdbf783016a189a680254e185b1da43c2c5</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-25.liferay.com/job/test-portal-source-format/3244/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-source-format/builds/3244/jenkins-report.html">here</a>.</h5></details></html>

2021-08-09 20:08 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-25.liferay.com/job/test-portal-source-format/3244/">test-portal-source-format#3244</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-source-format/builds/3244/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/alexcandidos/liferay-portal/pull/517">alexcandidos#517</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1552272424">[master] ci:test:sf - LucasAcacio &gt; alexcandidos - PR#517 - 2021-08-09[09:49:37]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-25.liferay.com/job/publish-testray-report/9849/">publish-testray-report#9849</a><br/></div></div>

2021-08-09 22:09 UTC, alexcandidos commented
Hi @LucasAcacio , Thanks for working on it!

The code looks good to me!

2021-08-09 22:09 UTC, alexcandidos commented
ci:forward

2021-08-09 22:10 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

The pull request will automatically be forwarded to the user `brianchandotcom` if the following test suites pass:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

2021-08-09 22:10 UTC, liferay-continuous-integration commented
Skipping previously passed test suites:
`ci:test:relevant`
`ci:test:sf`

2021-08-10 13:16 UTC, alexcandidos commented
ci:forward

2021-08-10 13:16 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

The pull request will automatically be forwarded to the user `brianchandotcom` if the following test suites pass:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

2021-08-10 13:16 UTC, liferay-continuous-integration commented
Skipping previously passed test suites:
`ci:test:relevant`
`ci:test:sf`

2021-08-10 13:17 UTC, liferay-continuous-integration commented
All required test suite(s) passed.
Forwarding pull request to `brianchandotcom`.
[Console](https://test-1-30.liferay.com/job/forward-pullrequest/19//consoleFull)

2021-08-10 13:17 UTC, liferay-continuous-integration commented
Pull request has been successfully forwarded to https://github.com/brianchandotcom/liferay-portal/pull/105322
[Console](https://test-1-30.liferay.com/job/forward-pullrequest/19//consoleFull)

2021-08-10 13:17 UTC, closed without merging