LRAC-8458
alexcandidos/liferay-portal pull request #529
Opened 2021-08-06 16:32 UTC by AfonsoHSantos

2021-08-06 16:32 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2021-08-07 01:02 UTC, alexcandidos commented
ci:test:sf

2021-08-07 01:02 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-31.liferay.com/job/test-portal-source-format/37/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-31.liferay.com//userContent/jobs/test-portal-source-format/builds/37/jenkins-report.html">here</a>.</b></p>

2021-08-07 01:04 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 2 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/85ec5558383ead431ef152d67df3af5c556ac69a">85ec5558383ead431ef152d67df3af5c556ac69a</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/AfonsoHSantos/liferay-portal/tree/LRAC-8458">LRAC-8458</a><br/>Branch GIT ID: <a href="https://github.com/AfonsoHSantos/liferay-portal/commit/2134554a4ef91737109bc2891e4c922d426ee027">2134554a4ef91737109bc2891e4c922d426ee027</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-31.liferay.com/job/test-portal-source-format/37/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-31.liferay.com/userContent/jobs/test-portal-source-format/builds/37/jenkins-report.html">here</a>.</h5></details></html>

2021-08-07 08:04 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-31.liferay.com/job/test-portal-source-format/37/">test-portal-source-format#37</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-31.liferay.com/userContent/jobs/test-portal-source-format/builds/37/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/alexcandidos/liferay-portal/pull/529">alexcandidos#529</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1551961952">[master] ci:test:sf - AfonsoHSantos &gt; alexcandidos - PR#529 - 2021-08-06[18:02:20]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-31.liferay.com/job/publish-testray-report/119/">publish-testray-report#119</a><br/></div></div>

2021-08-09 21:06 UTC, alexcandidos commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/analyticscloud/SegmentsList.testcase
> +		// TODO LRAC-8462 AssertUserIsInformedWhenThereAreNoDisabledSegments
hi @AfonsoHSantos , this test is a priority should be 3 according to our test map.

2021-08-09 21:06 UTC, alexcandidos commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/analyticscloud/SegmentsList.testcase
> +		// TODO LRAC-8461 PaginateSegmentList
hi @AfonsoHSantos , this test is a priority should be 3 according to our test map.

2021-08-09 21:08 UTC, alexcandidos requested changes
hi @AfonsoHSantos , could you please update the test priorities?

2021-08-09 21:11 UTC, AfonsoHSantos commented
ci:test:sf

2021-08-09 21:12 UTC, AfonsoHSantos commented
Hi @alexcandidos, i made the changes!

2021-08-09 21:12 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-30.liferay.com/job/test-portal-source-format/149/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-30.liferay.com//userContent/jobs/test-portal-source-format/builds/149/jenkins-report.html">here</a>.</b></p>

2021-08-09 21:15 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/99e68815843e30f8817d839e793fa0e7a854f91a">99e68815843e30f8817d839e793fa0e7a854f91a</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/AfonsoHSantos/liferay-portal/tree/LRAC-8458">LRAC-8458</a><br/>Branch GIT ID: <a href="https://github.com/AfonsoHSantos/liferay-portal/commit/24221e798011386af83e3cf6fb4f4d4528ca3b5f">24221e798011386af83e3cf6fb4f4d4528ca3b5f</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-30.liferay.com/job/test-portal-source-format/149/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-30.liferay.com/userContent/jobs/test-portal-source-format/builds/149/jenkins-report.html">here</a>.</h5></details></html>

2021-08-09 21:16 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-30.liferay.com/job/test-portal-source-format/149/">test-portal-source-format#149</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-30.liferay.com/userContent/jobs/test-portal-source-format/builds/149/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/alexcandidos/liferay-portal/pull/529">alexcandidos#529</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1552342786">[master] ci:test:sf - AfonsoHSantos &gt; alexcandidos - PR#529 - 2021-08-09[14:12:09]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-30.liferay.com/job/publish-testray-report/426/">publish-testray-report#426</a><br/></div></div>

2021-08-09 21:17 UTC, alexcandidos commented
Hi @AfonsoHSantos , Thanks for working on it!

The code looks good to me!

2021-08-09 21:18 UTC, alexcandidos commented
ci:forward

2021-08-09 21:18 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

The pull request will automatically be forwarded to the user `brianchandotcom` if the following test suites pass:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

2021-08-09 21:18 UTC, liferay-continuous-integration commented
Skipping previously passed test suites:
`ci:test:relevant`
`ci:test:sf`

2021-08-10 13:48 UTC, alexcandidos commented
ci:forward

2021-08-10 13:48 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

The pull request will automatically be forwarded to the user `brianchandotcom` if the following test suites pass:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

2021-08-10 13:48 UTC, liferay-continuous-integration commented
Skipping previously passed test suites:
`ci:test:relevant`
`ci:test:sf`

2021-08-10 13:56 UTC, liferay-continuous-integration commented
All required test suite(s) passed.
Forwarding pull request to `brianchandotcom`.
[Console](https://test-1-16.liferay.com/job/forward-pullrequest/262//consoleFull)

2021-08-10 13:56 UTC, liferay-continuous-integration commented
Pull request has been successfully forwarded to https://github.com/brianchandotcom/liferay-portal/pull/105332
[Console](https://test-1-16.liferay.com/job/forward-pullrequest/262//consoleFull)

2021-08-10 13:56 UTC, closed without merging